apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-gul8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-gul8@sha256:015fe09ab0630df5df668c5cddcaf23d001a71158ff3754f57360efb8c250e46
        name: my-nodejs
        resources: {}
status: {}
